DROP TABLE IF EXISTS public.profile CASCADE;

DROP TABLE IF EXISTS public.category CASCADE;

DROP TABLE IF EXISTS public.budget CASCADE;

DROP TYPE IF EXISTS public.e_category_type CASCADE;

DROP TYPE IF EXISTS public.e_currency CASCADE;

CREATE TYPE public.e_category_type AS ENUM ('INCOME', 'EXPENSE');

CREATE TYPE public.e_currency AS ENUM ('PHP', 'SGD');

CREATE TABLE public.profile (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 500) NOT NULL,
    last_name TEXT NULL DEFAULT '' :: TEXT,
    first_name TEXT NULL DEFAULT '' :: TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_profile_id PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE public.category (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid (),
    profile_id INTEGER NOT NULL REFERENCES public.profile (id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT NULL DEFAULT '' :: TEXT,
    type public.e_category_type DEFAULT 'EXPENSE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
) TABLESPACE pg_default;

CREATE TABLE public.budget (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid (),
    category_id UUID NOT NULL REFERENCES public.category (id) ON DELETE CASCADE,
    profile_id INT NOT NULL REFERENCES public.profile (id) ON DELETE CASCADE,
    start_date DATE NOT NULL DEFAULT NOW(),
    end_date DATE NOT NULL DEFAULT NOW(),
    interval INTEGER NOT NULL DEFAULT 1,
    amount FLOAT NOT NULL DEFAULT 0,
    currency public.e_currency DEFAULT 'PHP',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
) TABLESPACE pg_default;
